RobHofmann/HomeAssistant-GreeClimateComponent

climate.yaml
custom_components/gree/climate.py

**Fixed sleep mode operation**:
This is a solution to #44 
**Fix Health function activation**:
Currently it is only possible to operate health function in cool and dry mode. This is not a limitation of the device as health function (cold plasma caster) is not dependent on the mode of operation and can be activated/deactivated in every mode. Therefore I propose a change that allows that.
**RFC - 8 deg C Heat function**
This is implementation of RFC #46.
The input_boolean is working, mode is limited only to Heat as on real AC. 
The only thing missing is that when this mode is activated it would be good to display target temp as 8 deg C the same as on the device display. Maybe someone could add this or give me a hint how to do it quickly. Didn't want to mess up the temp refreshing/setting.

Fixes for sleep mode / health mode activation / RFC for 8℃ Heating mode

---

custom_components/gree/climate.py

In order to configure the AC in HA Gui, a unique id is neccesary. Without the Unique ID you cannot define e.g. a room in the GUI.

Unique ID added to custom component for better integration in Home Assistant

---

custom_components/gree/climate.py

Without this, calling climate.turn_on will always set climate mode to heat, see home-assistant climate component source code here https://github.com/home-assistant/core/blob/40b5605cafcf81925c6066545b0bc226ee78a4e4/homeassistant/components/climate/__init__.py#L546

Support turn_on

---

custom_components/gree/climate.py

changed async_track_state_change with async_track_state_change_eventaccording to  https://developers.home-assistant.io/blog/2024/04/13/deprecate_async_track_state_change/

async_track_state_change -> async_track_state_change_eventaccording

---

custom_components/gree/climate.py

- Added support for horizontal swing. Since ha's climate entity doesn't support horizontal swing, to enable operation on units that have this feature, component uses preset modes.
- Added support for new climate entity flags - TURN_ON, TURN_OFF according to https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/

Horizontal swing, new climate entity flags

---

README.md
custom_components/gree/climate.py

Added support for auto_light:
- when set auto_light: true in config unit will always turn light on when power on and turn light light off when power off. Light entity id should be set but is optional and can be used to control light for example in sleep mode
Added support for auto_xfan:
- when set auto_xfan: true in config unit will always turn on xFan in cool and dry mode. There is no need to set xfan entity id, even if it is set, it will be ignored
Added support for target temperature entity id
- when set target_temp: input_number... in config we can control target temperature with input_number helper. 
Useful when someone wants to build a custom layout, for example with custom:button_card. Input number should be declared with attributes min: 16 max: 30
Updated async_update_ha_state() …

Add support for auto_light and auto_xfan

---

README.md
custom_components/gree/climate.py

Add support for new version of encryption. It was mentioned https://github.com/tomikaa87/gree-remote/issues/52

add new encryption method

---

custom_components/gree/climate.py

Sets the unit within the integration to Celsius. The API sends/expects inputs as Celsius regardless of config state on the device. HA will translate the received temperatures according to the global units configuration.
This does NOT address the apparent jumps during updates to the temperature via the integration. As a guess, it's because the target_temp_step is also in Celsius (+/- 1°C).

Update unit of measurement within integration

---

README.md
custom_components/gree/climate.py

Solved problem of device unavailability if home assistant starts when devices are offline or have no power. From now on, devices are correctly added to the home assistant. There is a specific time interval when the home assistant checks whether the devices are online or not. If not, device is marked as unavailable until it appears on the network.

Device availability

---

custom_components/gree/manifest.json

Hi,
It is not always clear what exactly version you are using in HACS, as it always has 2.3.1 since that vesion.
Just reinstalled this component several times until realized the actual version is not 2.3.1, but 2.14.2.
I believe it's a good practive to always align version of release with version in manifest.json :)
Regards,
Dmitry

Up-to-date version in manifest.json

---

custom_components/gree/climate.py

- Fixed temp adjustment for Fahrenheit.  
-- Temperatures set weren't being accurately reflected on the lovelace dashboard due to F to C rounding.  
-- TemRec: this bit is used to distinguish between two Fahrenheit values -> https://github.com/tomikaa87/gree-remote?tab=readme-ov-file
- Rolled back to last good commit prior to the two most recent PRs and added in the conversion from that commit which was working the best of the most recent edits. 
- Refrained from readjusting '_unit_of_measurement' in down level methods and instead converted values where appropriate.  -- Much simpler to debug and manage

Fixed ambient temperature display and temperature set in F 

---

custom_components/gree/climate.py
custom_components/gree/manifest.json

I had Fahrenheit support coded up and tested last month, but got busy and wasn't able to get a PR made. It looks like [phirschorn](https://github.com/phirschorn) beat me to it! However, this update makes several notable improvements, simplifications, and bug fixes.
Most notably, I made the integration unit_aware (I know [phirschorn](https://github.com/phirschorn) tried a version of this), and fixed a bug with the HA UI display jumping around because of a need to convert to Fahrenheit from the **SetTem** and **TemRec** bits to display properly in HA. I also updated the version in the manifest.json.
**Summary:**
* Adds temperature awareness, but using HA units of measurement to determine SetTem and TemRec as well as display logic instead of temperature ranges (min_temp and max_temp). This …

Rework and Improvement of Fahrenheit Conversion

---

README.md
climate.yaml
custom_components/gree/climate.py
custom_components/gree/manifest.json

According to this reference: https://github.com/tomikaa87/gree-remote/ TemSen is offset by +40. However, [tomikaa87/gree-remote#31](https://github.com/tomikaa87/gree-remote/issues/31) suggests that the newer firmware (> 4.0) does not include the offset. After some testing with multiple users, this is not always reliable. Automatically determining if the offset should be there based on the raw temperature value seemed a little hacky, so I added some more sophisticated logic. I think this is the best way and is going to work 99.9% of the time.
* Automatically determines if offset is appropriate. Uses historical min/max historical TemSen values to best determine offset.
* Added ability for users to manually set boolean for the if offset is applied. (This overwrites automatic determination). …

Determine TemSen temperature offset automatically or manually. (#246)

---

custom_components/gree/climate.py
custom_components/gree/config_flow.py
custom_components/gree/translations/en.json

The modification allows sending silent commands without beeping both for manual control and in automations.
An example of how to assign an entity to toggle a beeper:
In the climate.yaml file:
beeper_entity_id: input_boolean.living_room_ac_beep
When the boolean is true it beeps, when it's false it doesn't.
Occasionally beeps even when false and requires toggling on, off for some reason.
Also a small correction for line 857.

Add beeper functionality

---

README.md

Split air conditioner unit - no additional steps were required beyond completing the Wifi setup as directed by the EWPE Smart app. I had to get the IP Address & Mac Addresses from my router as they are not shown in the app. I also set a static IP address for all of my units while I was there.
The default settings (incl. encryption) in the gree integration GUI worked fine. I have not looked into the optional functions, but all the major functions + temp were automatically exposed and work fine.
Note that the units take about 2 minutes to reset themselves after you press the MODE + WIFI combination and hear the beep (app does a bad job of explaining this). When it's reset the temporary direct Wifi network will appear, named for the last 6 digits of its mac address.

Add Argo ECOLIGHT 9000 with Wifi Module

---

README.md
climate.yaml
custom_components/gree/climate.py
custom_components/gree/icons.json
custom_components/gree/translations/de.json
custom_components/gree/translations/en.json
custom_components/gree/translations/he.json
custom_components/gree/translations/hu.json
custom_components/gree/translations/it.json
custom_components/gree/translations/pl.json
custom_components/gree/translations/ro.json
custom_components/gree/translations/ru.json

- Replaced all instances of `full_swing` with `swing_full` in horizontal swing modes to make it coherent with the swing modes format
- Updated the English translation for horizontal full swing from `Full swing` to `Swing in full range` for coherence
**Note: This might break your climate cards that use `full_swing` or its translation. Please update them with `swing_full` or its localized equivalent.**

Use swing_full in horizontal mode as well instead of full_swing for coherence

---

README.md
custom_components/gree/climate.py

Fixes #304
- Fixed beeper initialization to correctly handle both ON and OFF states at startup.
- Corrected and clarified log messages for beeper state changes.
- Improved README documentation for the beeper option.

Fix beeper init when toggle is false and correct reversed log messages

---

.vscode/settings.json
README.md
custom_components/gree/climate.py

**Summary**
Adds support for the MC31-00/F model and likely other VRF AC modules with sub-units.
**Details**
Matches Gree+ app behavior when adding a VRF AC:
`<sub_mac_address>@<parent_mac_address>
`
(Can be copied directly from the app.)
Changes are backward compatible and should not affect other devices.
**Bug Fixes**
- Resolved an issue in GreeGetValues where requesting a single value returned a list. 
SyncState expected a direct value, leading it to incorrectly assume certain features were unsupported.
- Resolved some acess to non-initialized values cauesd an exception.
**Known Issue**
For VRF AC units, state changes are not immediately reflected in the UI—they only appear after the periodic update() runs.
This does not affect other AC units.
I'm still investigating the issue, but …

Add support for Gree MC31-00/F Central Air Conditioner Remote Control Module

---

supported-devices.md

Added 3 Gree Clivia's (firmware version `v2.10` according to Gree app) using this integration a few weeks ago and still running perfect.
NOTE: needs encryption version 2 to work (otherwise devices are unavailable in Home Assistant)

Add Gree Clivia to list of supported devices

---

custom_components/gree/config_flow.py
custom_components/gree/gree_protocol.py
custom_components/gree/translations/en.json

Closes #365
Code might not be optimal, some repetition here and there, but it's by the book still.
It _seems_ like decoding the UDP response always uses the same encryption. So in theory we could show more info (model/firmware/etc) in the 2nd step, but I wanted to keep it simple for now.
First step:
Second step (will show manual config if no devices found):
Third step (will try to decode the data, on fail will show manual config with error and pre-filled fields)
Possible third step message:
On error when selecting a found device:

Add auto-discovery

---

custom_components/gree/sensor.py
custom_components/gree/translations/en.json

Also took the opportunity to standardize the file in order to use our `GreeEntityDescription` class.
Both sensors will need to be recreated/updated once the integration loads the new code. Either remove/re-add the entry or manually delete them both, then re-create entities so that the new sensors use the new id generated.

Add translatable names for room humidity and external temperature sensors
