custom_components/gree/climate.py

Replacing current temperature to None fixes drops during HA restart

Fixes drops in current temperature graph

---

custom_components/gree/climate.py

moved to inbuilt homeassistant.climate.const

partial translation

---

README.md
climate.yaml
custom_components/gree/climate.py

Big thanks for creating this curstom addon.
I like this one above the mqtt version but was missing some of the options that where available in the mqtt version (mqtt template switch).
I updated the code and tested it. Think it's ready to share.
Can you review/test it and let me know what you think?
Hope you find this an usefull addition as well.
Thanks in advance and regards.

Added support for lights, xfan, sleep and powersave mode.

---

custom_components/gree/manifest.json

I think it would be great to integrate the component to HACS (https://github.com/custom-components/hacs)

manifest.json for HACS

---

custom_components/gree/climate.py

No more on/off, but off/heat/cool etc shown as the state of this component.

Changed state to current operation mode

---

README.md
custom_components/gree/climate.py

This includes the needed changes for the 0.96 and higher versions of Home Assistant

New Climate Platform for HASS 0.96+

---

custom_components/gree/climate.py

Fix for missing temp display in #46 . 
Credit goes to @wacher74

Fix for HA temp display in 8degC heat mode

---

custom_components/gree/climate.py

Fix for 0.110 warning

---

README.md
custom_components/gree/climate.py

This adds an input boolean for the air/scavenging feature. While the manual mentions "scavenging", the app and HVAC itself say "Air" so I've used that in the code.
Tested on Argo Milo Plus
Closes #78

Add support for air/scavenging feature

---

custom_components/gree/manifest.json

Now it need the version tag on manifest.json

Update manifest.json to support HA 2021.3.0 requirements

---

README.md

Works with CASCADE BORA-CWH09AAB.

New tested device

---

README.md

I tried to integrate Sinclair ASH-12BIV with this component and it works really well.

Added AC model to README.md

---

custom_components/gree/climate.py

This might break some features, but it restores the main feature: being able to control your AC.
@toughvj please take a look at this. My AC's are no longer unavailable anymore. However the light/autolight features seem to have stopped working.

Some fixes for None types, cleanup and extra checks

---

custom_components/gree/climate.py

See details mentioned in this issue - https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/205
Summary of Changes
Detect and apply the AC’s TemUn flag
• Read TemUn (0 = °C, 1 = °F) from the device payload
• Set self._unit_of_measurement to “°C” or “°F” at setup and on every refresh
• Log the detected display unit for easier debugging
Fix target‑temperature display
• Update UpdateHATargetTemperature() to convert the raw SetTem value correctly based on TemUn
• Ensure that setting a target in Fahrenheit now writes back in °F rather than converting it to °C
Fix current‑temperature display
• Update UpdateHACurrentTemperature() to use the same TemUn flag when converting the built‑in temperature (TemSen)
• Avoid double‑conversion (formerly treated Fahrenheit reading as Celsius …

Respect Device Temperature Unit (TemUn) for Both Current and Target Temperatures

---

custom_components/gree/climate.py

- Renamed UpdateHACurrentTemperature to UpdateHAAmbientTemperature for better clarity 
- Refactored UpdateHACurrentTemperature/UpdateHAAmbientTemperature  
- Adjusted _async_update_current_temp to handle temp conversions between HA and AirCon unit
- Removed redundant block added in last PR oops

Null temp fix and temp conversion handling 

---

custom_components/gree/climate.py

Move a signficant number of the _LOGGER.info() calls to _LOGGER.debug(). Still left a fair amount of info calls, especially on setup.
Addresses: https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/250

Reduce excessive info logging. #250

---

custom_components/gree/climate.py

Implemented bi-directional (to and from the unit) fractional Celsius temperatures support using the TemRec bit (which was only used for Fahrenheit previously). Due to protocol limitations, it is limited to 0.5 degree increments, but the integration will round to the nearest 0.5 degree if set to target_temp_step is set to less than 0.5 degree C.
No effect for Fahrenheit users since they already make use of fractional degrees Celsius.
Fixes: #237

Fix fractional temperatures (C). #237

---

README.md
custom_components/gree/translations/it.json

Add Italian translation

---

custom_components/gree/translations/pl.json

after the last update, the translations seem to have been generated by AI, with this commit I am restoring more fitting translations

Update polish translation

---

custom_components/gree/climate.py

fix [issue #320](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/320)
This change seems to work with both my module (MC00-31/F) and the one in the issue (ME00-31/C5)
I've also tested it on my Non-VRF AC (Amcor Inverter 18NG) to make sure it is not affecting others

fix VRF support

---

README.md
custom_components/gree/__init__.py
custom_components/gree/climate.py
custom_components/gree/sensor.py

Closes #267 
I noticed there are 2 fields for the outside temperature sensor that return the same value, so I just used one of them.
They're added as separate sensors and also extra attributes to the climate entity.

Add support for outside temperature and room humidity sensors

---

README.md

Related to #336
Also removed a broken link in the sources section.

Add comprehensive switches and controls documentation

---

custom_components/gree/gree_protocol.py

fix incorrect parse of mac_addr

[BugFix] Gree VRF module is ME31-00/C3 stopped working after upgrade to v3

---

custom_components/gree/gree_protocol.py

Adding support for auto discovery of sub units of VRF AC.
tested with my VRF module (Gree MC31-00/F).
for unknown reason, not all sub units are being returned from the api, not sure if that's a bug or some kind of a limitation of the API.

[AutoDiscovery] Add Support for VRF sub-units auto discovery
